Tanmay/email verification
Spiral-Forge/Protege-Web pull request #66
Opened 2022-01-13 15:16 UTC by tnmyk

Closes #60

2022-01-13 16:40 UTC, tnmyk commented
Closes #51

2022-01-14 09:43 UTC, tnmyk commented on src/App.js
>            <Switch>
sadsadasdwdsad

2022-01-14 09:46 UTC, nitashadhingra requested changes
Login page: DialogueContent:
Email not verified
    Please check your inbox and verify your email to sign in.

Login page:
before verification check, also check if user used that id to register in the first place or not

2022-01-14 09:47 UTC, nitashadhingra requested changes
On signup page, after clicking on AGREE on guidelines, there's no popup or navigation of page 
Popup text should be : "Please check your inbox and verify your email"

2022-01-14 13:28 UTC, nitashadhingra requested changes
1. Can u change all the window.alerts to Dialogs (No title needed)
2. Incorrect password check should also be added!! (flow of checks: registered? -> verified? -> correct password)

2022-01-15 09:43 UTC, merged